layout_spectrum: 0.3518736402038485
typography_spectrum: 0.3540021814405918
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.5121208433993161
  lightness: 0.5394675079733133
  saturation: 0.5907847839407623
  rhythmicContrast: 0.8133041246328503
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: INVERTED CULTURE
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Inverted Culture
description: monochrome emotions where memories and imagination collide
purpose: []
